# Development Dockerfile
FROM python:3.11.1-slim-buster

WORKDIR /src

# Install dependencies
COPY ./pyproject.toml /src
COPY ./poetry.lock /src
RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev python3-dev gcc curl
RUN curl -sSL https://install.python-poetry.org | python - --version 1.3.1
ENV PATH="${HOME}/.local/bin:$PATH"
RUN ${HOME}/.local/bin/poetry config virtualenvs.create false
RUN ${HOME}/.local/bin/poetry install --only main

# Debugpy installation
RUN ${HOME}/.local/bin/poetry run pip install debugpy

EXPOSE 5678

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

