version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../src:/src
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port for debugpy
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - IS_DEV=true
