name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.3.1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Black
        run: poetry run black --check src/

  type-check:
    name: Type Check with Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.3.1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Mypy
        run: poetry run mypy src/

  test:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.3.1

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run Tests
        run: poetry run pytest src/tests
